version: '3.9'

services:
  db:
    image: postgres
    restart: always
    container_name: db-local
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      TZ: "Asia/Seoul"
    profiles:
      - local
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
      - ${POSTGRES_CONF_PATH}:/etc/postgresql.conf