version: '3.9'

services:
  db:
    image: postgres
    restart: always
    container_name: db-local
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      TZ: "Asia/Seoul"
    profiles:
      - local
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
      - ${POSTGRES_CONF_PATH}:/etc/postgresql.conf

  ## minio 설정
  minio:
    image: bitnami/minio
    container_name: minio
    ports:
      - "19000:9000"
      - "19001:9001"
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
      MINIO_VOLUMES: /minio-storage
      MINIO_BROWSER: "on"
    volumes:
      - ${MINIO_DATA_PATH}:/minio-storage