spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        show_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_SECRET_ID}
            scope: profile, email

feedflow:
  jwt:
    secret: ${JWT_SECRET_KEY}